# Generated by Django 5.2.12 on 2026-03-24 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_user_reminder_user_rtr_user_studysession_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='LinkedIn', max_length=50)),
                ('scrapedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
